<?php

class PxlMailchimp_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_mailchimp';
    protected $title = 'PXL Mailchimp';
    protected $icon = 'eicon-email-field';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_style","label":"Style","tab":"style","controls":[{"name":"form_id","label":"Form ID","type":"text"},{"name":"style","label":"Style","type":"select","options":{"style-default":"Default"},"default":"style-default"},{"name":"input_color","label":"Color Input","type":"color","selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"email\"]":"color: {{VALUE}};"}},{"name":"input_background","label":"Background Input","type":"color","selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"email\"]":"background-color: {{VALUE}};"}},{"name":"input_color_button","label":"Color Button","type":"color","selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"submit\"]":"color: {{VALUE}};","{{WRAPPER}} .pxl-mailchimp.style-default svg path":"fill: {{VALUE}};"}},{"name":"btn_gradient","label":"background type","type":"background","control_type":"group","types":["gradient"],"selector":"{{WRAPPER}} .pxl-mailchimp.style-default .btn"},{"name":"border_type","label":"Border Type","type":"select","options":{"":"None","solid":"Solid","double":"Double","dotted":"Dotted","dashed":"Dashed","groove":"Groove"},"selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"email\"]":"border-style: {{VALUE}} !important;"}},{"name":"border_width","label":"Border Width","type":"dimensions","selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"email\"]":"border-width: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}} !important;"},"condition":{"border_type!":""},"responsive":true},{"name":"border_color","label":"Border Color","type":"color","selectors":{"{{WRAPPER}} .pxl-mailchimp.style-default [type=\"email\"]":"border-color: {{VALUE}} !important;"},"condition":{"border_type!":""}},{"name":"max_width","label":"Max Width","type":"slider","control_type":"responsive","range":{"px":{"min":100,"max":1920}},"selectors":{"{{WRAPPER}} .pxl-mailchimp > div":"max-width: {{SIZE}}{{UNIT}};"}},{"name":"min_width","label":"Min Width","type":"slider","control_type":"responsive","range":{"px":{"min":100,"max":1920}},"selectors":{"{{WRAPPER}} .pxl-mailchimp > div":"min-width: {{SIZE}}{{UNIT}};"}},{"name":"content_align","label":"Content Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-mailchimp":"justify-content: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}