<?php

class PxlProductDetail_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_product_detail';
    protected $title = 'Pxl Product Detail';
    protected $icon = 'eicon-posts-ticker';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"tab_layout","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/digicove\/wp-content\/themes\/digicove\/elements\/templates\/pxl_product_detail\/img-layout\/layout1.jpg"}},"prefix_class":"pxl-product-detail-layout-"}]},{"name":"source_section","label":"Source","tab":"content","controls":[{"name":"query_type","label":"Select Query Type","type":"select","default":"recent_product","options":{"recent_product":"Recent Products","best_selling":"Best Selling","featured_product":"Featured Products","top_rate":"High Rate","on_sale":"On Sale","recent_review":"Recent Review","deals":"Product Deals","separate":"Product separate"}},{"name":"taxonomies","label":"Select Term of Product","type":"select2","multiple":true,"options":[]},{"name":"product_ids","label":"Products id (123,124,135...)","type":"text","default":"","condition":{"query_type":"separate"}},{"name":"post_per_page","label":"Post per page","type":"text","default":"10"},{"name":"style","label":"Style","type":"select","options":{"style1":"Default","style2":"Style 2","style3":"Style 3"},"default":"style1"}]},{"name":"section_style_title","label":"Style Color","tab":"style","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-product-detail .woocommerce-product-inner .woocommerce-product-content .woocommerce-product--title a":"color: {{VALUE}} !important;","{{WRAPPER}} .pxl-product-detail .woocommerce-product-inner .woocommerce-product-content .woocommerce-available-product--numbers .woocommerce-available-product--number":"color: {{VALUE}} !important;"}},{"name":"title_color_hover","label":"Title Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-product-detail .woocommerce-product-inner .woocommerce-product-content .woocommerce-product--title:hover a":"color: {{VALUE}} !important;"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'pxl-countdown','pxl-progressbar','digicove-progressbar' );
}