<?php

class PxlTableGrid_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_table_grid';
    protected $title = 'Pxl Table Grid';
    protected $icon = 'eicon-lock-user';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"team","label":"Team","type":"repeater","default":[],"controls":[{"name":"title","label":"Title","type":"text","label_block":true},{"name":"social","label":"Social","type":"pxl_links"}],"title_field":"{{{ title }}}"}]},{"name":"section_style","label":"Style","tab":"style","controls":[{"name":"h_width","label":"Width","type":"slider","control_type":"responsive","size_units":["px","%"],"range":{"px":{"min":0,"max":3000}},"selectors":{"{{WRAPPER}} .pxl-wrap-table .pxl-table":"width: {{SIZE}}{{UNIT}};"}},{"name":"width_e","label":"Width Col End","type":"slider","control_type":"responsive","size_units":["px","%"],"range":{"px":{"min":0,"max":3000}},"selectors":{"{{WRAPPER}} .pxl-wrap-table .pxl-table-inner .wrap-table:last-child":"min-width: {{SIZE}}{{UNIT}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-table--title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-table--title"},{"name":"pos_color","label":"Item Color","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > span":"color: {{VALUE}} !important;","{{WRAPPER}} .pxl-table--item > a":"color: {{VALUE}} !important;"}},{"name":"pos_typography","label":"Item Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-table--item > a"},{"name":"odd_color","label":"Background Item Color Odd","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > span:nth-child(odd)":"background-color: {{VALUE}} !important;","{{WRAPPER}} .pxl-table--item > a:nth-child(odd)":"background-color: {{VALUE}} !important;"}},{"name":"even_color","label":"Background Item Color Even","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > a:nth-child(even)":"background-color: {{VALUE}} !important;","{{WRAPPER}} .pxl-table--item > span:nth-child(even)":"background-color: {{VALUE}} !important;"}},{"name":"bg_button_color","label":"Background Button","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > a > span":"background-color: {{VALUE}} !important; border-color :  {{VALUE}} !important;"}},{"name":"button_color","label":"Color Button","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > a > span":"  color: {{VALUE}} !important;"}},{"name":"button_color_hv","label":"Color Button Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > a > span:hover":"color: {{VALUE}} !important;"}},{"name":"bg_button_color_hv","label":"Background Button Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-table--item > a > span:hover ":"background-color: {{VALUE}} !important; border-color :  {{VALUE}} !important;"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'imagesloaded','isotope','pxl-post-grid' );
}